### ISSUE TITLE
Feature request: support cloud-init to initialize linux VMs

### ISSUE THREAD

**Issue by sspreitzer** [oVirt/terraform-provider-ovirt#38] opened 2018-07-22 12:50 UTC
Hi there

Thanks for all the good work! I am hereby requesting cloud-init/sysprep functionality to be added to this project.
It is a great way to automate VM configuration.

Thank you

**Comment by imjoey** [comment] 2018-07-23 01:09
Thanks, it's a typical feature. We will add it with a high priority. 😄

**Comment by bmanojlovic** [comment] 2018-07-23 21:55
i am confused which part of cloud-init? i mean i am already using centos images without any issues 
only what is maybe missing is script on boot? Am i missing something else, or you meant exactly that

**Comment by yalinglee** [comment] 2018-07-24 07:13
I would also love to be able to use cloud-init to set the hostname and kick off the Chef bootstrapping process!

**Comment by imjoey** [comment] 2018-07-24 07:40
@bmanojlovic  The [Initialization](
http://ovirt.github.io/ovirt-engine-api-model/4.3/#types/initialization) struct contains the cloud-init/sysprep related configurations. The IP (address/subnet_mask/gateway) defined in  `network_interface` is part of this.

**Comment by bmanojlovic** [comment] 2018-07-24 08:30
I understood what he was talking about, that is why i asked. ( I already used cloud-init image in my tests as can be seen in issue with diskattachments).
Anyway like i said yes "runcmd" ("missing is script on boot" part of my post) is missing and would be very nice addition to network initialization part.

Other part that is still a bit of "issues" is VM instance is not started on creation.

**Comment by imjoey** [comment] 2018-07-24 08:42
yes, pull request #33  has fixed the not-started-on-creation issue of vm.

**Comment by sspreitzer** [comment] 2018-07-24 14:39
@bmanojlovic You can either attach your own cloud-init ISO for example or you can have ovirt manage it for you. I prefer the API way instead of the ISO way as that is much better for programming dynamic cloud-init.

https://www.ovirt.org/develop/release-management/features/virt/cloud-init-integration/

**Comment by imjoey** [comment] 2018-07-25 12:36
@sspreitzer @yalinglee   #44 has added support for several configurations in cloud-init/sysprep functionality.

**Comment by imjoey** [comment] 2018-08-20 05:16
@yalinglee  reopen to track your issue. There has a similar one reported [1], and got fixed in [2]. I will check and fix it soon. Thanks.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1593239
[2]: https://gerrit.ovirt.org/#/c/93044/

**Comment by imjoey** [comment] 2018-08-22 12:59
hi @yalinglee , this has been fixed by #57 . Currently only `cloud-init` for Linux VMs is supported. I will add `sysprep` for Windows VMs later.

**Comment by yalinglee** [comment] 2018-09-05 23:47
@imjoey I just confirmed that cloud-init works as expected now. Thank you!

**Comment by imjoey** [comment] 2018-09-06 00:36
😄  I'll keep this issue opened until Windows VM is supported for sysprep.

**Comment by sspreitzer** [comment] 2018-09-06 16:15
@imjoey Thank you for your contribution and work!

**Comment by bwillif1** [comment] 2019-03-18 18:08
Are there still plans to support Windows VMs with sysprep? I'd like to be able to automate a windows vm configuration. 
Cloudbase-init also looks like a viable solution for initializing windows guests. https://cloudbase.it/cloudbase-init/

**Comment by imjoey** [comment] 2019-04-01 14:42
Hi @bwillif1 , sorry for the late reply. Adding support for Windows VMs with sysprep is still in the work list. Thanks for your recommended solution and I'll investigate on it soon. Thanks again for your contribution.

**Comment by rgolangh** [comment] 2019-06-19 08:01
VM.initialization is working - @sspreitzer @imjoey I'm thinking maybe we should close this and open a new issue strictly for sysprep, or just rename this issue

**Comment by imjoey** [comment] 2019-06-19 12:44
@rgolangh @sspreitzer  I would prefer close this after we open a new issue for `sysprep` feature, which could let us more focus on only **one** thing. 😄

**Comment by imjoey** [comment] 2019-07-10 03:03
The feature requested for initializing windows VMs with sysprep will be traced within #158 . Please follow it for the latest updates. This issue is closed right now.

**Closed by imjoey** 2019-07-10 03:03 UTC
Labels: enhancement
